-- Extrair TODOS os dados do testesetimo (que NÃO funciona)
-- vs testesexto (que FUNCIONA)

-- auth.users
SELECT 
    'testesetimo (FALHA)' as origem,
    instance_id,
    id,
    aud,
    role,
    email,
    LEFT(encrypted_password, 20) as password_prefix,
    email_confirmed_at,
    invited_at,
    confirmation_token,
    confirmation_sent_at,
    recovery_token,
    recovery_sent_at,
    email_change_token_new,
    email_change,
    email_change_sent_at,
    last_sign_in_at,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    created_at,
    updated_at,
    phone,
    phone_confirmed_at,
    phone_change,
    phone_change_token,
    phone_change_sent_at,
    confirmed_at,
    email_change_token_current,
    email_change_confirm_status,
    banned_until,
    reauthentication_token,
    reauthentication_sent_at,
    is_sso_user,
    deleted_at,
    is_anonymous
FROM auth.users
WHERE email = 'testesetimo@hotmail.com'

UNION ALL

SELECT 
    'testesexto (FUNCIONA)' as origem,
    instance_id,
    id,
    aud,
    role,
    email,
    LEFT(encrypted_password, 20) as password_prefix,
    email_confirmed_at,
    invited_at,
    confirmation_token,
    confirmation_sent_at,
    recovery_token,
    recovery_sent_at,
    email_change_token_new,
    email_change,
    email_change_sent_at,
    last_sign_in_at,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    created_at,
    updated_at,
    phone,
    phone_confirmed_at,
    phone_change,
    phone_change_token,
    phone_change_sent_at,
    confirmed_at,
    email_change_token_current,
    email_change_confirm_status,
    banned_until,
    reauthentication_token,
    reauthentication_sent_at,
    is_sso_user,
    deleted_at,
    is_anonymous
FROM auth.users
WHERE email = 'testesexto@hotmail.com';
